// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2704.comandrobot.subsystems;


import org.usfirst.frc2704.comandrobot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;
import com.ctre.phoenix.motorcontrol.ControlMode;

/**
 * Represents the drivetrain of the robot.
 * Takes a joystick, has control scheme implemented internally.
 */
public class Drivetrain extends Subsystem {
    private VictorSP rightfront;
    private VictorSP rightrear;
    private SpeedControllerGroup speedControllerGroup1;
    private VictorSP leftfront;
    private VictorSP leftrear;
    private SpeedControllerGroup speedControllerGroup2;
    private DifferentialDrive differentialDrive1;
    
    // increasing this value causes turn speed to be more higher per degree turned on the joystick.
    private double turnSpeedModifier = 0.50;

    // increasing this value causes the forwards/backwards speed to be larger for any joystick input.
    private double moveSpeedModifier = 1;

    // increasing this value makes the magnitude of robot twist required to enter "turn mode" higher.
    private double turnDeadZone = 0.5;

    // this value makes it so that when the robot leaves the turn speed dead zone, it doesn't jerk.
    private double turnadjust = turnDeadZone*turnSpeedModifier;

    public Drivetrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        rightfront = new VictorSP(0);
        addChild("right front",rightfront);
        rightfront.setInverted(false);
        
        rightrear = new VictorSP(1);
        addChild("right rear",rightrear);
        rightrear.setInverted(false);
        
        speedControllerGroup1 = new SpeedControllerGroup(rightfront, rightrear  );
        addChild("Speed Controller Group 1",speedControllerGroup1);
        
        
        leftfront = new VictorSP(2);
        addChild("left front",leftfront);
        leftfront.setInverted(false);
        
        leftrear = new VictorSP(3);
        addChild("left rear",leftrear);
        leftrear.setInverted(false);
        
        speedControllerGroup2 = new SpeedControllerGroup(leftfront, leftrear  );
        addChild("Speed Controller Group 2",speedControllerGroup2);
        
        
        differentialDrive1 = new DifferentialDrive(speedControllerGroup2, speedControllerGroup1);
        addChild("Differential Drive 1",differentialDrive1);
        differentialDrive1.setSafetyEnabled(true);
        differentialDrive1.setExpiration(0.1);
        differentialDrive1.setMaxOutput(1.0);

        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
    public void takejoystickinputs(Joystick joystick1)
    {
        if (Math.abs(joystick1.getZ())<turnDeadZone) {
            // forward speed is the modified motor impulse to move the robot.
            double forwardspeed=joystick1.getY()*moveSpeedModifier;
            differentialDrive1.tankDrive(forwardspeed,forwardspeed);
        } else {
            // turn speed is the modified motor impulse to turn the robot.
            double turnspeed=joystick1.getZ()*turnSpeedModifier;
            // make turning not jerky by decreasing the absolute value of turnspeed.
            // talk to tom for further explanation.
            turnspeed = turnspeed<0 ? turnspeed+turnadjust : turnspeed-turnadjust;
            // if there's a problem with the code, it's probably right here,
            // and it it safe to comment it out.
            differentialDrive1.tankDrive(turnspeed,-turnspeed);
        }
    }
    public void stop(){ 
        differentialDrive1.tankDrive(0, 0);
    }
    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

